# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  #  - name: Docker Setup Compose
  #    uses: docker/setup-compose-action@v1.2.0
  #    with:
  #      version: v2.35.1
  #      cache-binary: false
    - name: docker-compose down
      run: docker compose down
    - name: docker-compose up
      run: docker compose up -d --build
          
